prompts = ['Alcohol use', 'Drugs use', 'Smoking drugs', 'LGBTQ Content',
           'Expressions of Nudity', 'Expressions of Sexuality',
           'Expressions of Profanity',
           'Expressions of Hate Speech', 'Expressions of Violence',
           'Normal Conversational and Discussion',
           'Opinions and Beliefs', 'Emotional Content',
           'Narratives and Stories',
           'Instructions and Directions', 'Questions and Answers',
           'Problem Solving', 'Conflict and Resolution',
           'Cultural and Societal Insights',
           'Entertainment and Humor',
           'Technical and Specialized Knowledge',
           'Language and Linguistic Analysis', 'Personal Information', 'Cultural Expressions',
           'Sarcasm and Irony', 'Hesitation and Uncertainty', 'Agreements and Disagreements',
           'Social Relationships', 'Expressions of Gratitude',
           'Expressions of Apology', 'Learning and Education', 'Negotiation', 'Influence and Manipulation',
           'Authority and Power Dynamics', 'Motivation', 'Politeness and Rudeness',
           'Greetings and Farewells',
           'Rituals and Traditions', 'Public Speaking',
           'Criticism and Feedback', 'Speculation and Hypothetical',
           'Nostalgia',
           'Abstract Concepts and Philosophical Discussions',
           'Health and Wellness Information', 'Environment and Weather',
           'Travel and Experiences', 'Technology and Innovation',
           'Product and Service Recommendations', 'Legal and Ethical Discussions',
           'Creative and Artistic Expression']
