settings1 = {"a photo inside, of a bar establishment": "bar",
             "a photo inside, of a bedroom, bed, bedchamber": "bedroom",
             "a photo inside bathroom": "bathroom",
             "a photo inside kitchen": "kitchen",
             "a photo on the street": "street",
             "a photo inside, of a sports, pitch, racing track, athletes, competitive physical activity": "sports field",
             "a photo inside, of a park, trees, benches, statues, ponds in a park": "park",
             "a photo inside a nightclub, music club, discotheque, disco club": "nightclub",
             "a photo of a dark place, a dark chamber, a dark abandoned place, crypt": "dark place",
             "a photo of a blurry place": "blurry place",
             "a photo inside the college": "college",
             "a photo of buildings": "buildings",
             "a photo inside laboratory, manufacturing unit": "laboratory",
             "a photo inside jungle": "jungle",
             "a photo inside a car, train, aeroplane, boat": "vehicles",
             "a photo of a swimming pool": "swimming pool",
             "a photo of a church or monuments": "monument",
             "a photo of ocean": "ocean",
             "a photo of mountains": "mountains",
             "a photo inside a shop": "shop",
             "a photo inside a house": "house",
             "a photo inside a restaurant": "restaurant",

             "a photo of photographs": "others",
             "a photo of group of people": "others",
             "a photo of a person": "others",
             "a photo of a close up shot of a person": "others",
             "a photo of a logo": "others",
             "a photo of a sign board": "others",
             "photo frames on the wall": "others",
             "a close up of an object": "others",
             "a photo of an object": "others",
             "a photo of others": "others",
             "an image of entire black screen": "others",
             }

settings2 = {
    "day time, sunshine": "day time",
    "night time": "night time",
    "red light": "red light",
    "blue light": "blue light",
    "low light": "low light",
    "a photo of others": "others",
    "an image of entire black screen": "others",
}

settings3 = {
    "image focussing on a zoomed, close-up of face": "closeup",
    "a close up of person's front,side,rear face": "closeup",
    "image of close up of object": "closeup",
    "image of an enlarged,zoomed face": "closeup",
    "a close up of glass,bottle,food": "closeup",
    "image of close up of human body part holding object": "closeup",
    "image framing frontal upper human body and not close-up": "front",
    "image of side,tilted,aligned face of person": "side",
    "image of a peron's back or backhand": "rear",
    "a photo of others": "others",
    "a photo of blur screen": "others",
    "image of entire black screen": "others",
    "a photo": "others",
}

people_count = {"image containing single person": "single",
                "image containing closeup of face": "single",
                "image containing couple, two people, or two person": "couple",
                "image containing a man and a woman": "couple",
                "image containing group of people, gathering": "group",
                "image containing three or more people, group": "group",
                "a photo of others": "others",
                "image of entire black screen": "others",
                "a photo of unidentified object": "others",
                }

activities_content = {

    "image showing an empty or unoccupied space": "blank",
    "image showing a still or blank or uneventful background or black background": "blank",
    "image showing a frame with little visibility or blur background": "blur",
    "image showing passive or monotonous or insignificant event": "blank",
    "image out of focus or blurry due to motion or camera shake": "blur",
    "image showing an unrecognized activity": "still",
    "image showing a close-up shot of an unrecognized object": "still",
    # Credits, Warning, watermark, logo, production logo
    "image showing centered words or credits on a screen": "still",
    "image showing sentences written in the middle of the screen": "still",
    "image showing statutory warning written on the screen": "still",
    "image showing a movie production company or movie studio logo or movie title still": "still",
    "image showing a brand logo or service logo or trademark logo or organization logo or a product logo": "still",
    # Cropped parts
    "image showing cropped hands or cropped legs or cropped body": "still",
    "image showing a cropped bodies of a couple": "still",
    "image showing a cropped face": "still",
    "image showing a cropped unrecognized object": "still",
    # Majority of frames
    "image showing an unrecognized object filling majority of the frame": "still",
    "image showing face or hands or fingers or legs filling the majority of the frame": "still",
    "image showing a person's body filling majority of the frame": "still",
    # Objects
    "image showing the use of a device or a gadget": "still",
    "image showing any objects that are typically used on a regular basis or household objects": "still",
    "image showing water bottles or fruit juice bottles or water containers or cola tins": "still",
    "image showing a cabinet full with different soft drink bottles": "still",
    "image showing daily used utensils": "still",
    "image showing daily used vehicles": "still",
    "image showing daily used tools": "still",
    "image showing an empty bed in the bedroom": "still",

    # Vehicles
    "image showing movement of automobiles": "still",
    "image showing a shot of a car": "still",
    # People, Group, Person:
    "image showing gathering of group of people, people roaming around": "gathering",
    "image showing group of men and women enjoying themselves, engaging in a activity": "enjoying",
    "image showing group of people engaged in a local gathering": "gathering",
    # close up Shots
    "image showing a side view of a close up of a face": "still",
    "image showing a close up shot of a unrecognized object": "still",
    "image showing a close up shot of face": "still",
    "image showing a close up shot of faces of group of people": "still",
    "image showing a close up shot of group of people": "still",
    "image showing a close up shot of limp arm": "still",
    # long shots
    "image showing a long shot of a person": "still",
    "image showing a person with a clean face with open mouth, showing drops of sweat on the face": "still",
    "image showing an orgasm expression on the face": "expressions",
    # Animal:
    "image showing animal roaming freely in its natural habitat": "animal activity",
    "image showing a human petting or holding an animal affectionately": "human and animal activity",
    "image showing humans playing with animals": "human and animal activity",
    "image showing animal enjoying themselves": "animal activity",
    "image showing animal mating or mating habit": "animal activity",
    # Couple activities
    "image showing couple hiking in nature, walking and talking": "hiking",
    "image showing a man and a woman standing next to each other and looking around": "standing",
    "image showing a man and a woman sleeping": "sleeping",
    "image showing a couple sitting very close to each other, indicating their affection": "affection",
    "image showing couple's close faces, suggesting they are looking each other out of affection": "affection",
    "image showing a man and a girl sitting side by side with a pen in hand, looking around or talking": "talking",
    "image showing two friends sitting in the restaurant and talking": "talking",
    "image showing two friends enjoying themselves": "enjoying",
    "image showing a girl and a boy enjoying themselves": "enjoying",
    "image showing a couple engaged in a daily routine activity": "daily activity",
    "image showing an unrecognized activity between the couple": "unrecognized activity",
    "image showing an unrecognized activity of a drug addict": "unrecognized activity",
    "image showing friends standing next to each other talking, looking": "neutral",
    "image showing some people standing or talking or looking around": "talking",
    "image showing men standing or talking or looking around": "talking",
    "image showing girls standing or talking or looking around": "talking",
    # Solo activities (male, female)

    "image showing a person driving a car or a vehicle": "driving",
    "image showing a person clicking photo using the camera": "clicking photo",
    "image showing a woman dressed in a bra and panties or lingerie": "clothing",
    "image showing a cropped image of a beautiful woman, with a focus on the face": "still",
    "image showing a person wearing clothing specifically designed for swimming or water activities": "clothing",
    "image showing a person reading or writing": "reading/writing",
    "image showing a guy playing a musical instrument while relaxing with friend at home": "playing instrument",
    "image showing individuals who appear to be alive with eyes open": "still",
    "image showing a woman is sitting, talking, looking around": "talking",
    "image showing a man is sitting, talking, looking around": "talking",
    "image showing a cowboy looking around": "standing",
    "image showing a masked person": "still",
    "image showing a full shot of a person": "still",
    "image showing a clean and clear face": "still",
    "image showing clean and clear clothes": "still",
    "image showing a man shouting out loud": "expressions",
    "image showing a angry man, focus on face": "expressions",
    "image showing a person is standing surrounded by a group of people": "gathering",
    "image showing the body of a person": "still",
    "image showing a woman in a bikini covering her fully": "still",
    "image showing a body in a red or pink dress like blood": "still",
    "image showing a person looking in the mirror": "standing",
    "image showing a person talking, oral": "talking",
    # People Activities:
    "image showing people engaged in a particular sports activity": "sports activity",
    "image showing discussion between group of people": "talking",
    "image showing people or couple hugging each other": "hugging",
    "image showing couple or people sleeping or resting": "sleeping",
    "image showing people sleeping in the dark or at night": "sleeping",
    "image showing people walking": "walking",
    "image showing people gesturing": "gesturing",
    "image showing joyful people dancing, enjoying themselves": "dancing",
    "image showing people inside a store or shop": "group activity",
    "image showing people in a park or outdoor setting": "gathering",
    "image showing people exercising": "exercising",
    "image showing people using public transportation": "transportation",
    "image showing people holding a child or baby": "kids activity",
    "image showing people enjoying themselves on the street": "street activity",
    "image showing people engaged in a hobby or pastime": "hobby",
    "image showing people performing a work-related activity": "work-related activity",
    "image showing people performing a leisure or relaxation activity": "leisure activity",
    "image showing people performing a everyday or routine activity": "routine activity",
    "image showing people playing musical instruments and singing": "singing",
    "image showing people sitting around and enjoying their company": "sitting",
    "image showing conversation between people on a street corner": "talking",
    "image depicting groups of the crowd on the field or in the room": "group activity",
    "image showing People Talk about the Project during a Break": "talking",
    "image showing friends, glass of water": "group activity",
    # Expressions:
    "image depicting emotions or feeling expressing through their facial expression": "expressions",
    "image depicting affection in a friendly or familial context": "expressions",
    "image showing facial or lips expressions indicating pouting or mouth movement": "expressions",
    "image depicting signs of tiredness such as drooping eyelids or slouching posture": "expressions",
    # Settings:
    "image showing a natural landscape": "still",
    "image showing an urban setting": "still",
    "image showing a building or architecture": "still",
    "image showing a sunset or sunrise": "still",
    "image showing waterfall or river": "still",
    "image showing a plant or tree": "still",
    "image showing a night sky": "still",
    "image showing a beach or ocean": "still",
    "image showing a desert or mountainous terrain": "still",
    "image showing a forest or jungle": "still",
    "image showing a snowy or icy environment or icy floor": "still",
    "image showing a city skyline": "still",
    "image showing a traffic scene or highway": "still",
    "image showing a body of water or lake": "still",
    "image showing a building interior or interior design": "still",
    "image showing a neutral outdoor scene or natural setting": "still",
    "image showing a crypt, cellar or basement": "still",
    "image showing fire around": "still",
    # *gun
    "image showing Armed robbers used the gun to robbery the money, Uses Gun in Armed Robbery": "violence",
    "image showing Cops Using a gun to intimidate the Suspect": "violence",
    "image showing Gun Models Display": "violence",
    "image showing soldiers armed with gun weapons": "violence",
    "image depicting firearms weapons visible in the image, such as a handgun, rifle, or shotgun": "violence",
    "image depicting long-range weapons visible in the image, such as crossbows or sniper rifles": "violence",
    "image showing Group of people brandishing guns": "violence",
    "image showing the soldiers brandish their gun weapons, military operation in action": "violence",
    "image showing a man brandishes a pistol in his hands": "violence",
    "image showing a Armed and dangerous criminal brandishing a gun": "violence",
    "image showing Guns and ammunition placed in a wooden table": "violence",
    "image showing weapons laid out on the table arms trafficking, different rifles on the counter in the gun shop, clandestine sale of weapons, illegal purchase of weapons, firearms on the table": "violence",
    "image showing a person aiming a gun for threatening": "violence",
    "image showing the assembly or production of firearms": "violence",
    "image showing Collection of rifles and carbines, various firearms hang on special mounts on the wall, weapon background": "violence",
    "image showing a group of people are shown firing their weapons in a battle, explosions and gunfire filling the air": "violence",
    "image showing a man firing the bullets from a gun on a person": "violence",
    "image showing a man aiming the holding gun": "violence",
    "image showing a commando holding the rifle": "violence",
    "image showing a cowboy holding pistol": "violence",
    "image showing a person brandishing a gun in a liquor store or in a bar": "violence",
    "image showing a gun weapon kept on a table along with beer or whiskey bottles or glass": "violence",
    # *sword
    "image showing The murderer is holding a knife trying to hurt a weak woman": "violence",
    "image showing a person in a monkey cap use a sharp knife want to kill the victim": "violence",
    "image showing Closeup hand holds vintage knife in the evening light": "violence",
    "image depicting bladed weapons visible in the image, such as knives, swords, or machetes": "violence",
    "image showing a warrior brandishes an ax for violent act of executions": "violence",
    "image showing a hand with bloody knife outdoor": "violence",
    "image showing a person holding knife with blood dripping": "violence",
    "image showing someone is stabbing other person with a sharp knife": "violence",
    "image showing people brandishing knives or other sharp objects as weapons": "violence",
    "image showing two people engage in a sword fight, clanging their blades together and dodging each other's attacks": "violence",
    "image showing a crypt, cellar or basement with many swords weapons kept their": "violence",
    # *war artillery
    "image showing bow and arrow ina war zone": "violence",
    "image showing military equipment in open space": "violence",
    "image showing any vehicles or machinery that could be used as weapons, such as tanks, bulldozers, or drones": "violence",
    "image showing any explosive devices, such as bombs or grenades": "violence",
    "image showing ancient war artillery in the ancient war scenario": "violence",
    "image shown using heavy artillery to destroy an enemy stronghold, with buildings crumbling and explosions everywhere": "violence",
    # *stick
    "image depicting stick assault": "violence",
    "image showing a man beating attackers using a stick": "violence",
    "image showing group of people engaged in a brutal fistfight using a stick": "violence",
    "image showing a group of martial artists practicing stick-fighting techniques": "violence",
    # blood_gore
    # gore
    "image showing bloody wound or gore on the body": "violence",
    "image showing gored body": "violence",
    "image showing human organs in a jar": "violence",
    "image showing decaying flesh": "violence",
    "image showing visible wounds or injuries in the image, such as cuts, bruises, or abrasions": "violence",
    "image showing a gored and bloody naked body, showing deep lacerations and stab wounds": "violence",
    # significant_blood
    "image showing visible injuries and cuts on a person's body resulting in severe blood loss": "violence",
    "image showing any bloodstains or lots of blood on the ground or other surfaces": "violence",
    "image showing people or animals bleeding or hemorrhaging": "violence",
    "image showing a violent act leading to significant blood loss": "violence",
    "image showing a person vomiting blood": "violence",
    "image showing a person with a clean face with blood dripping down from the face": "violence",
    # some_blood
    "image depicting any acts of physical violence, such as punching, kicking, or choking, bleeding, injury shown": "violence",
    "image showing some blood that has been shed, especially as a result of violence": "violence",
    "image depicting blood or gore in the context of animal abuse or assault or hunting": "violence",
    "image showing an injured man with bleeding from his face": "violence",
    "image showing drops of blood on the face": "violence",
    # no_blood
    # *mutilated_body
    "image showing a person with rotted or decomposed face with blood dripping down from the face": "violence",
    "image showing a person with rotted or decomposed face with gore": "violence",
    "image showing a rotted or decomposed body part with gore": "violence",
    "image showing a rotted or decomposed animal with gore all over the body": "violence",
    "image showing a charred face with blood on the face": "violence",
    "image showing a charred body with blood on the body": "violence",
    "image showing a burned or charred body beyond recognition": "violence",
    "image showing a burned or charred head beyond recognition": "violence",
    "image showing a burned body, burning": "violence",
    "image showing blood drops on the clothes": "violence",
    "image showing a person is burning surrounded by a group of people": "violence",
    "image showing a person is cutting the human head using a sword": "violence",
    "image showing a person examining the mutilated body": "violence",
    "image showing a person examining the human dead body or corpse": "violence",
    "image showing torture or other extreme violence that have resulted in mutilation or dismemberment": "violence",
    "image showing a bloody dismemberment body": "violence",
    "image showing the dismemberment body parts in blood": "violence",
    "image showing a person dismembering the body of a victim": "violence",
    "image showing a mutilated body of a person": "violence",
    # *visible_injuries
    "image showing a injured person among the lifeless human bodies": "violence",
    "image showing a injured person with significant blood loss and clothes are covered with blood": "violence",
    "image showing a injured person with injuries are visible on the body": "violence",
    "image showing a seriously injured person": "violence",
    # *dead_body
    "image showing many dead bodies on the ground after a brutal fight": "violence",
    "image showing a dead mutilated corpse": "violence",
    "image showing a dead body or corpse": "violence",
    "image showing a brutal fight with blood spread all over the place": "violence",
    "image showing a dead body or corpse with blood": "violence",
    "image showing a person holding a dead body or a corpse with blood": "violence",
    # violent acts:
    "image showing the victims brutally assaulted, indicating violent act": "violence",
    "image showing the victim tied behind their backs or strapped their head and legs restrained, indicating violent act of executions": "violence",
    "image showing Impaled heads on spear brutal ancient execution method": "violence",
    "image showing a person in the guillotine, Executioner and axe, indicating violent acts": "violence",
    "image showing a person with tied up and locked with rope in the abandoned place, infringement hostage": "violence",
    "image depicting signs of sexual violence or sexual assault": "violence",
    # Whole frame have violence seen
    "image showing aftermath of violent act": "violence",
    "image showing violent acts of bombings or explosives, indicating explosion aftermath": "violence",
    "image depicting a bomb explodes in a crowded marketplace, causing chaos and destruction": "violence",
    # fighting
    "image showing group of people engage in a brutal fistfight, kicking and punching each other on the ground": "violence",
    # *prescriptions shown
    "image showing a prescription bottle": "substance use",
    "image showing a person taking daily dose of a prescription pill": "substance use",
    "image showing doctor wearing white uniform with stethoscope consulting older woman patient, holding glass bottle with medicine, prescription, explaining treatment plan, senior people healthcare concept": "substance use",
    "image showing Doctor, researcher or scientist hand in blue glove holding vaccine and syringe with needle vaccination for a person, medicine vial dose injection": "substance use",
    # *marijuana shown
    "image showing rolling a marijuana joint, Man preparing and rolling marijuana cannabis joint, Drug use": "substance use",
    "image depicting holding a small bag of marijuana, with them proceeding to roll a joint, indicating drug use": "substance use",
    # *psychedelic shown
    "image showing a drug addict holding drug pills on tongue": "substance use",
    # *hard drugs shown
    "image depicting a group of people huddled around a table, counting piles of white powder, syringes and pills": "substance use",
    "image depicting someone is shown using a lighter to heat up a substance on a spoon before injecting it": "substance use",
    "image showing drug syringe and cooked heroin on spoon": "substance use",
    "image showing a drug addict preparing drugs with a spoon and lighter, white powder and a syringe": "substance use",
    "image showing Drugs, addiction and cocaine on table with pills, social problem and crime in narcotics": "substance use",
    "image showing drug use, addiction, substance abuse, addict with lighter and spoon preparing dose of crack cocaine on street": "substance use",
    "image showing Plastic packet, lines and pile of cocaine on black background": "substance use",
    "image showing cocaine with rows, rows and lines of powder to be tested, with a drool blade beside it and syringes": "substance use",
    "image showing cocaine or other drugs cut with card on mirror, hand dividing white powder narcotic": "substance use",
    "image showing used and discarded drug paraphernalia": "substance use",
    "image showing narcotics drug paraphernalia for Heroine and Cocaine": "substance use",
    "image showing Heroin, Cocaine and narcotics drug paraphernalia are placed on old wood": "substance use",
    "image showing discarded Syringe on waste ground by heroin user": "substance use",
    "image showing Close up shot of a drug addicts with narcotics drug paraphernalia shown next to it": "substance use",
    "image showing drug addict with syringe and needle in hand, focus on syringe and needle": "substance use",
    "image depicting a man holding a cocaine powder substance in a packet or pouch": "substance use",
    "image showing the pile of discarded needles, cigarette butts, and other narcotics drug paraphernalia scattered on the floor": "substance use",
    "image showing alcohol, drugs, pills on a wooden background": "substance use",
    # manufacturing
    "image depicting people packing illegal drugs in a packet, indicating drug manufacturing assembly": "substance use",
    "image showing Shot of Sterile Pharmaceutical Manufacturing Laboratory where Scientists in Protective Coverall's Do Research, Quality Control and Work on the Discovery of new Medicine": "substance use",
    "image showing pharmacy medicine capsule pill in production line at medical factory": "substance use",
    "image showing Packing of white powder in packets": "substance use",
    "image showing the pile of illegal drug packets kept in a shelf": "substance use",
    "image showing underground Drug Laboratory Clandestine Chemists Wearing Protective Masks and Coveralls Mix Chemicals": "substance use",
    "image showing drug packets in a drug manufacturing set up": "substance use",
    "image showing drug Dealer takes packed drug brick out of the suitcase and cuts it to try a sample": "substance use",
    "image showing illegal drug manufacturing, Handling of drugs, drug treatment": "substance use",
    "image showing Cannabis plantation in the Chui valley, Bushes of cannabis by a stern plant, Leaves of narcotic plants for the manufacture of anasha. Hemp. marijuana": "substance use",
    "image showing Police conducting a drug search at the illegal drug manufacturing laboratory": "substance use",
    "image showing cocaine warehouse, plastic bags with cocaine in a box, indicating illegal drugs traffic": "substance use",
    "image showing Cocaine packets being weighted Drugs are being seized by people from cartels infinite production": "substance use",
    "image showing research scientist Conducts Experiments by Synthesising Compounds with use of Dropper and Plant in a Test Tube": "substance use",
    "image showing a Person in a gas mask, chemical mask": "substance use",
    # *injecting shown
    "image showing a injecting heroin in the body with the use of syringe": "substance use",
    "image showing a drugs addicted injecting heroin in his arm, Drug addict with syringe using drugs": "substance use",
    "image showing a Doctor Injecting a Patient With Syringe To Collect Blood Sample": "substance use",
    "image showing nurse with the syringe injects the vaccine to the patient lying in the hospital room bed, wearing protective gloves and medical surgical mask": "substance use",
    # *smoking shown
    "image showing Smoking marijuana (weed, cannabis)": "substance use",
    "image showing group of drug addicts smoking cannabis": "substance use",
    # *snorting shown
    "image depicting a line of white powder is shown being snorted off a flat surface": "substance use",
    "image showing a addict is snorting cocaine powder with rolled banknote": "substance use",
    "image showing the action of snorting cocaine powder lines": "substance use",
    "image showing a drug addict snorting and sniffing cocaine lines on mirror with rolled banknote": "substance use",
    # *oral shown
    "image showing Close up of happy person hold meds and water glass take contraception pill at home, smiling millennial female use daily dose of vitamins, supplements drugs or meds, health care concept": "substance use",
    "image showing sick ill person hold two pills on hand pouring capsules from medication bottle take medicine, close up view": "substance use",
    # selling shown
    "image showing narcotics dealer drug holding bag with cocaine drug powder, Cocaine in plastic packet": "substance use",
    "image showing mafia narcotics drug deal, narcotics hard drugs shown around": "substance use",
    "image showing a drug dealer holding a cocaine drug powder pouch and selling to friends": "substance use",
    "image showing drug selling, drug pouch in hand, holding cocaine packet": "substance use",
    #
    "image showing narcotics dealer Drug selling, drug sale": "substance use",
    # tobacco shown
    "image showing a person lights a cigarette for smoking": "substance use",
    "image showing Close up of hands hold cigarette in hand. There are glasses and cup of drink on table": "substance use",
    "image showing a person lighting a cigarette, getting nicotine, unable to resist to unhealthy habit": "substance use",
    "image showing individuals smoking or holding a lit cigarette in their hand": "substance use",
    "image showing any depictions of tobacco products, including cigarettes or cigars, that might suggest tobacco use": "substance use",
    "image showing whole lots of cigarettes or cigarette packet kept on the surface": "substance use",
    "image showing several ashtrays filled to the brim with cigarette butts, evidence of the chain-smoking habits": "substance use",
    # tobacco smoking and shown
    "image showing individuals who appear to be smoking, even if the cigarette is not clearly visible": "substance use",
    "image showing a person smoking cigarette near people smelling pollution, passive smoking concept": "substance use",
    "image showing a person holding smoking a cigarette in hand, Cigarette smoke spread": "smoking",
    "image showing a cool man smoking a cigarette on the street": "substance use",
    "image showing group of friends smoking cigarettes together outdoors": "substance use",
    "image showing couple smoking, cigarette shown": "substance use",
    "image showing a man and smiling woman smoking cigarettes during break at work on city street": "substance use",
    "image showing a person smokes on a break, smoking a cigarette in the office, focus on cigarette": "substance use",
    "image showing a group of employees smoking cigarette at a break in a relaxed atmosphere outside": "substance use",
    "image showing People Talk about the Project during a Break while Smoking cigarette on the Balcony": "substance use",
    "image showing side view of a person sitting and blowing smoke": "substance use",
    "image showing a man inhaling of a vapor with electronic cigarette, vape flavor liquid chemicals, use of e-cigarettes": "substance use",
    "image showing a guy smoking marijuana joint while relaxing with friend at home": "substance use",
    "image showing a tobacco user smoking cigarette with another person visible in the frame": "substance use",
    "image showing a person smoking a cigarette by holding cigarette in mouth": "substance use",
    "image showing People smoking cigarettes at public place outdoors": "substance use",
    "image showing a girl discussing with a man and holding a cigarette in mouth, smoking on a street corner": "substance use",
    "image showing a man enjoying smoking cigarette, focus on the cigarette, holing cigarette in hand and mouth": "substance use",
    # alcohol Shown
    "image showing alcohol bottles shown and cigarette shown": "substance use",
    "image showing Desperate, alcoholic man, liquor bottles shown around him, indicating alcohol addiction": "substance use",
    "image showing Empty bottles of alcohol": "substance use",
    "image showing a person holding a beer bottle at the corner of the frame": "substance use",
    "image showing Set of strong alcoholic drinks in glasses and shot glass in assortent: vodka, rum, cognac, tequila, brandy and whiskey": "substance use",
    "image depicting Group of friends cheering with champagne and beer": "substance use",
    "image depicting Bottles of alcohol and spirits at a restaurant bar, large variety of imported and domestic labels, brands and supplies for making cocktails and drinks ": "substance use",
    "image showing a Bartender preparing to make cocktail, Shelves with bottles of alcohol in background": "substance use",
    "image showing a Close up of man's hand holding crystal glass of whiskey or brandy": "substance use",
    "image showing Cheerful smiling person's holding glass with alcohol beverages and laughing": "substance use",
    "image showing a girl or a boy chooses wine in supermarket. person reads labels on bottles of wine in supermarket": "substance use",
    "image showing beer bottles or beer cans kept on the table": "substance use",
    "image showing alcohol cabinets and shelving for liquor storage at the bar": "substance use",
    "image showing glasses of red and white wine being offered": "substance use",
    "image depicting people say cheers over a liquor, indicating alcohol use": "substance use",
    "image depicting implied alcohol use": "substance use",
    "image depicting Alcohol consumption among youth, friends forcing boy to drink beer, bad company": "substance use",
    "image showing people sitting together at beach and having a party. Group of friends cheers with beers at the beach": "substance use",
    "image showing whisky with ice in a crystal drinking glass": "substance use",
    "image showing a variety of cocktail glasses in martini glasses are displayed on a bar top in a pub. The hands of people are shown holding the glasses": "substance use",
    "image showing profile side view photo of a person sitting with alcohol bottle of beverage": "substance use",
    # alcohol Shown and consumption:
    "image showing people sit around a table at a bar, drinks in hand and cigarettes burning in ashtrays, "
    "smoking cigarettes": "substance use",
    "image showing a silhouette of anonymous alcoholic person drinking behind bottles of alcohol": "substance use",
    "image showing Upset man drinker alcoholic sitting at bar counter with glass drinking whiskey alone, sad depressed addicted drunk guy having problem suffer from alcohol addiction abuse": "substance use",
    'image showing Group of people drinking alcohol while discussing': "substance use",
    "image showing Group of party people, men and women, drinking beer in a pub or bar": "substance use",
    "image showing happy friends drinking beer and clinking glasses at bar or pub": "substance use",
    "image depicting a crowded bar, showing patrons drinking and laughing, with glasses and bottles of alcohol on every table": "substance use",
    "image showing a person taking a sip of whiskey straight from the bottle, indicating alcohol use": "substance use",
    "image depicting Romantic Couple Enjoying alcohol Together": "substance use",
    "image depicting people consuming alcohol beverages or alcoholic drinks": "substance use",
    "image depicting people sitting around and enjoying drinking alcohol beverages or alcoholic drinks": "substance use",
    "image showing a woman drinking alcohol with a bottle or a glass": "substance use",
    "image showing a man drinking alcohol with a bottle or a glass": "substance use",
    "image showing Diverse People Friends Hanging Out Drinking alcohol": "substance use",
    "image showing a beautiful woman smiles and feels happy while having dinner and a glass of red wine with a person not shown in a photo": "substance use",
    "image showing friends drinking alcohol and talking": "substance use",
    "image showing Group of friends having party, smoking and drinking alcohol": "substance use",
    "image showing Group of people smoking and drinking while discussing": "substance use",
    # *bdsm
    "image depicting erotic practices of engaging in fetishistic behaviors, such as bondage, BDSM, or other kinks": "NSFW",
    "image showing set of erotic toys for BDSM. The game of sexual slavery with a whip, gag and leather blindfold": "NSFW",
    # *bestiality
    "image depicting sexual acts that is considered as bestiality": "NSFW",
    # *group sex
    "image showing sexual act of threesome or foursome": "NSFW",
    "image depicting group sex or orgy": "NSFW",
    "image showing group of men and group of women enjoying and engaged in a sexual activity of group sex": "NSFW",
    # *kissing
    "image showing kissing or smooching or romantic lip-lock": "kissing",
    # *making out
    "image showing a romantic couple, man and woman making love": "NSFW",
    "image showing a romantic sexy couple, man and woman having a foreplay": "NSFW",
    "image showing sensual passionate playful couple kissing making love, seductive sexy attractive woman on top embracing touching arousing tempting lover enjoying foreplay together": "NSFW",
    "image showing sexually suggestive poses or gestures, such as individuals touching or caressing another person's body": "NSFW",
    "image depicting beautiful intimate couple making love, couple having sex": "NSFW",
    "image depicting a Almost stripped man and woman in a loving embrace": "NSFW",
    # *masturbation
    "image showing sexual act of masturbation, jerking the penis or fingering the vagina for sexual pleasure": "NSFW",
    "image showing woman masturbating, touching her genitals for sexual pleasure": "NSFW",
    "image showing sexy woman in a underwear, touching herself": "NSFW",
    "image showing a sexy girl playing, touching with herself, orgasm, cuddling herself": "NSFW",
    "image showing the concept of masturbation, male needs, lust, desire, loneliness": "NSFW",
    # *necrophilia
    "image depicting necrophilia, a type of sexual attraction towards or a sexual act involving corpses": "NSFW",
    # *oral sex
    "image depicting a couple in a oral sex position, man touching the groin area by mouth": "NSFW",
    "image showing erotic oral sex position, a woman enjoying the best oral sex ever": "NSFW",
    "image showing close up shot of passionate couple having oral sex, intercourse": "NSFW",
    "image showing erotic oral sex position, man enjoying giving sexual satisfaction to his girl": "NSFW",
    # *sex toy
    "image showing sex toy's like dildos or vibrators": "NSFW",
    "image showing a Woman holding a dildo or vibrator, sex toy": "NSFW",
    # *vaginal
    "image depicting a sexual pose, sex poses illustration of man and woman": "NSFW",
    "image showing attractive sexy couple having sexual intercourse, sexual act of vaginal sex or penetrative sex": "NSFW",
    "image showing a man and a woman having hardcore genital sex, sexual intercourse": "NSFW",
    "cropped image of beautiful passionate couple having vaginal sex, sexual intercourse": "NSFW",
    "image depicting a close up shot of passionate couple having sex, sexual intercourse": "NSFW",
    # *same sex
    "image showing a lesbian couple (two girls) kissing or smooching or romantic lip-lock": "NSFW",
    "image showing a gay couple (two men) kissing or smooching or romantic lip-lock": "NSFW",
    "image showing a gay couple (two men) having anal sex": "NSFW",
    "image showing a lesbian couple (two girls) making out": "NSFW",
    "image showing a gay couple (two men) making out": "NSFW",
    # *front_female
    "image showing a upper naked body of a female, with focus on breast or boobs": "NSFW",
    "image showing a nude woman, exposing breast or boobs": "NSFW",
    "image showing a girl striping exposing her breast or boobs": "NSFW",
    "image showing close up shot of a girl's breast or boobs": "NSFW",
    "image showing a naked woman sitting, breast and nipples visible": "NSFW",
    "image showing a girl exposing her nipples, having sex": "NSFW",
    # *front_male
    "image showing upper naked body of a man, with focus on bare chest and nipples": "NSFW",
    "image showing a naked man sitting, chest visible": "NSFW",
    "image showing a nude man, exposing chest and nipples": "NSFW",
    "image showing naked man enjoying and smoking cigarettes": "NSFW",
    # *full_female
    "image showing a female's full naked frontal body including breast, nipples and vagina or vulva": "NSFW",
    "image showing a side view of a completely naked woman, full nudity": "NSFW",
    "image showing a completely naked gorgeous seductive woman lying on bed, full nudity": "NSFW",
    # *full_male
    "image showing a male's full naked frontal body including chest, nipples and penis or dick, full nudity": "NSFW",
    "image showing a side view of a completely naked man, full nudity": "NSFW",
    # *genitals_displayed
    "image showing naked baby showing genitals": "NSFW",
    "image showing clearly visible exposed genitals": "NSFW",
    "image showing close-up shot of genitals, vagina or penis": "NSFW",
    # *rear_view
    "image showing a female full naked back body including bare back and ass or buttocks": "NSFW",
    "image showing a male full naked back body including bare back and ass or buttocks": "NSFW",
    "image showing the lower naked body, with focus on buttocks or ass": "NSFW",
    "image showing the butt crack, ass": "NSFW",
    # all views / couple
    "image depicting groups of the fully naked crowd on the field or in the room": "NSFW",
    "image showing a completely naked man and a completely naked woman sleeping or sitting next to each other": "NSFW",
    "image depicting naked people enjoying themselves exposing their private body parts": "NSFW",
    "image showing a woman dressed in a revealing clothes or exposing dress and her private parts are visible from the dress": "NSFW",
    "image showing a side view of the completely naked couple in a sex position or making out": "NSFW",
    "image showing a woman with a breast and a man with bare chest": "NSFW",
    # *painting
    "image depicting a painting of fully naked body including breast and nipples and genitals": "NSFW",
    # *blowup dolls
    "image depicting a naked blow up doll, a type of anthropomorphic sex toy": "NSFW",
    # *statue
    "image depicting sculptures that resemble genitalia or other sexualized body parts": "NSFW",
    "image depicting statues that depict nudity or intimate body parts": "NSFW",
    # *mannequin
    "image depicting mannequins that are shown without clothing or that appear to be displaying intimate body parts": "still",
    # profanity
    "image depicting gestures using the middle finger": "gesturing",
    "image depicting the middle finger being used in combination with profanity": "gesturing",
}



