objects = [
    "People",
    "Vehicles (Cars, Trucks, Bicycles)",
    "Pedestrians",
    "Animals",
    "Bags and Luggage",
    "Weapons",
    "Suspicious Packages",
    "Fire",
    "Smoke",
    "Intruders",
    "License Plates",
    "Bicycles",
    "Motorcycles",
    "Emergency Vehicles",
    "Security Personnel",
    "Briefcases",
    "Access Cards or Badges",
    "Identification (ID) Cards",
    "Machinery and Equipment",
    "Drones",
    "Unattended Objects",
    "Hazardous Materials",
    "Crowds and Congregations",
    "Face Masks",
    "Handheld Devices (Smartphones, Tablets)",
    "Abandoned Vehicles",
    "Lost Children",
    "Medical Equipment",
    "Construction Materials",
    "Retail Merchandise",
    "Trains",
    "Buses",
    "Planes",
    "Boats",
    "Bicycle Helmets",
    "Money or Cash Transactions",
    "Computers and IT Equipment",
    "Safety Signs",
    "Closed-Circuit Television (CCTV) Cameras",
    "Elevators and Escalators",
    "No-Entry Zones",
    "Protective Barriers (e.g., Bollards)",
    "First Aid Kits",
    "High-Value Assets",
    "Art and Antiques",
    "Hazmat Suits",
    "Hygiene and Sanitary Supplies",
    "Building Entrances and Exits",
]
